### PR TITLE
Update generated-code.md

### PR DESCRIPTION
**Pull request by sinisa-andric**

### CODE REVIEW

**Comment by ejona86** [comment]
@zasweq can you review?

**Review by zasweq — APPROVED** [review]
LGTM.

**Comment by zasweq** [comment]
Approved, looks like I don't have write access though so my approval doesn't count.

**Review by ejona86 — APPROVED** [review]

**Comment by ejona86** [comment]
@zasweq, yeah, I was expecting to follow after you.

**Comment by zasweq** [comment]
Cool, thanks :)!

**Pull request merged**
