### PR TITLE
Create getting-started.md

### PR DESCRIPTION
**Pull request by Supermajestcd**

### CODE REVIEW

**Comment by arvindbr8** [comment]
There seems to be a duplicate submission https://github.com/grpc/grpc.io/pull/1087. Please close out the dup and we can take a look at the real one.

**Review by chalin — CHANGES_REQUESTED** [review]
Each language (or almost so) has a Getting Started page. I'm not sure that it makes sense to create yet another. I'm also not sure which need this is meant to fulfill, that isn't already met by the current documentation. Would you care to elaborate the motivation behind this submission? 

Also, parts of this page are copied verbatim from other pages.

I'm going to close this PR. Feel free to comment, offer more context and reopen if you still fill that there is added value here.

/cc @ejona86 @gnossen @thisisnotapril

**Comment by gnossen** [comment]
@temawi This seems pretty well-written.

**Comment by ANA885874** [comment]
Parabéns pelos 100 milhões de desenvolvedores.

**Comment by ANA885874** [comment]
Em qui., 26 de jan. de 2023 às 15:41, Richard Belleville <
***@***.***> escreveu:

**Comment by chalin** [comment]
Thanks for the feedback @gnossen! If you feel like you'd like to champion the addition of this page, let me know and I'll reopen and assign to you.

**Pull request closed without merging**
