### PR TITLE
Update Go quickstart to suggest using latest version

### PR DESCRIPTION
**Pull request by karanssh**
Updated the Go quickstart guide to suggest installation of latest version of `protoc-gen-go` and `protoc-gen-go-grpc`. Also added the versioned info as an option.

---

Edit(@chalin)

Preview: https://deploy-preview-964--grpc-io.netlify.app/docs/languages/go/quickstart/

### CODE REVIEW

**Review by dfawley — COMMENTED** [review]
These examples expect certain versions to be used.  While it might be reasonable to update the versions here to the latest (1.28 and 1.2), I don't think we should recommend using `@latest`, personally.

What prompted this change?

**Comment by karanssh** [comment]
> What prompted this change?

I did want to update the version to the latest ones, but I thought adding a note about `@latest` might be helpful to some people? I can make it such that we have only the latest version in the `@version_number` field

**Comment by dfawley** [comment]
> I did want to update the version to the latest ones, but I thought adding a note about @latest might be helpful to some people? I can make it such that we have only the latest version in the @version_number field

I would definitely prefer to keep this guide air-tight, and allowing the version of these tools to fluctuate without our control can potentially result in something that doesn't function properly for the user anymore.  I think it's gratuitous to explain to users how to use Go itself, but if you want to add separate a note explaining that the user can change the version numbers to the string "latest" in order to get the most recent versions, I would be okay with it.  If you do that, please also mention that this guide was written assuming the versions indicated, and not the latest versions.

**Comment by karanssh** [comment]
@dfawley , I think that's very reasonable, I updated the PR to just use the latest versions instead, since you mentioned those are fine. I think `@latest` or `@version` in a separate note might be outside the scope of this doc. Is this fine?

**Comment by karanssh** [comment]
I did run basic greeter server and compiled a proto file into it's generated code - but I didnt run a full test suite if that's what you are asking

**Comment by dfawley** [comment]
> I did run basic greeter server and compiled a proto file into it's generated code - but I didnt run a full test suite if that's what you are asking

That should be fine.  The example doesn't directly reference the generated code or anything, so I think as long as the basic regnerate + run works fine, then we're good to go.  @chalin, does this LGTY?

**Review by chalin — APPROVED** [review]
Thanks for the updates to the versions. LGTM

Nit: **please remove the extra blank lines** that you added around the code-block

**Comment by chalin** [comment]
> The example doesn't directly reference the generated code or anything, so I think as long as the basic regnerate + run works fine, then we're good to go. @chalin, does this LGTY?

Right, and yes this LGTM.

**Comment by chalin** [comment]
> Nit: **please remove the extra blank lines** that you added around the code-block

Actually, never mind, I can do that cleanup for you.

**Comment by chalin** [comment]
Thanks all!

**Pull request merged**
