### PR TITLE
Add Markdown support for page descriptions

### LINKED ISSUE #199: Error Handling page has raw markdown link in description
At https://grpc.io/docs/guides/error/ , we see:
> This page describes how gRPC deals with errors, including gRPC's built-in error codes. Example code in different languages can be found \[here](https://github.com/avinassh/grpc-errors).

I thought it'd be an easy syntax fix, but looking at the page https://github.com/grpc/grpc.io/blob/master/content/docs/guides/error.md it looks like the problem is that markdown is unsupported in the description.

It's unclear if it should use HTML \<a> tags, or whether the link just needs to move into the page's body.

### PR DESCRIPTION
**Pull request by lucperkins**
Fixes #199

### CODE REVIEW

**Comment by chalin** [comment]
We probably shouldn't need to support markdown in descriptions, and #199 has been closed (by editing out the markdown from the description). I'd suggest closing this PR for now.

**Comment by lucperkins** [comment]
I guess I don’t see any reason not to, for example for backticked code

**Comment by chalin** [comment]
IMHO, we can revisit this if ever the need arises, but currently, none of the descriptions contain markdown (now that the Error page's description has been edited). But, it's your call.

**Comment by chalin** [comment]
@lucperkins - can we close this PR?

**Comment by lucperkins** [comment]
@chalin I don't have permissions to merge this on my own. My call is that it should stay, as it does no harm and we've already seen a case of someone expecting to be able to use Markdown in a page description.

**Comment by chalin** [comment]
#199 has been addressed and so we don't need this functionality. We can revisit later if/when needed.

**Comment by chalin** [comment]
IMHO, there are enough moving parts to avoid future proofing for a feature that I'm not convinced is desirable. Yes, I did mention "your call", but after further reflection, I changed my mind. Thanks for your understanding.

**Pull request closed without merging**
