### PR TITLE
Updates the grpc-web instructions to run the basic example

### PR DESCRIPTION
**Pull request by rluders**
Updates the docker commands that weren't working.
It is now like the ones at the repository: https://github.com/grpc/grpc-web

### CODE REVIEW

**Comment by chalin** [comment]
Hi @rluders! Thanks for the PR.

@Jennnny @grpc/grpc-web-team: do you approve?

**Comment by chalin** [comment]
Pinging @stanley-cheung and @grpc/grpc-web-team: do you approve?

My impression is that the current commands are just fine.

**Comment by chalin** [comment]
Actually, I'd rather keep the commands as they are; in particular, run detached servers and then shutting them down with another command. Closing. Might revisit this later when reassessing how much of the `grpc-web` hello-world example and tutorial to move over here.

@stanley-cheung - if you have any objections let me know.

**Comment by stanley-cheung** [comment]
No objections. Just down to personal preferences.

**Pull request closed without merging**
