### PR TITLE
doc: Use f-strings instead of %-s in Python quickstart

### PR DESCRIPTION
**Pull request by Mariatta**
Use modern f-string formatting instead of %-s.

### CODE REVIEW

**Comment by easwars** [comment]
@Mariatta : Could you please sign the CLA. Thanks.

**Comment by Mariatta** [comment]
CLA signed. Thank you.

**Review by gnossen — APPROVED** [review]
Thanks for noticing this!

**Comment by gnossen** [comment]
@ejona86 Can you please merge?

**Review by ejona86 — APPROVED** [review]

**Pull request merged**
