### PR TITLE
[WIP] Improve aesthetic of Presentations and Talks page

### PR DESCRIPTION
**Pull request by lucperkins**
This PR proposes a more compact way to list presentation videos. You can see the end result here:

https://deploy-preview-129--grpc-io.netlify.com/docs/talks

I'm open to suggestions on this.

### CODE REVIEW

**Comment by chalin** [comment]
Thanks for the proposal. The current page design works better for me, both on mobile and desktop. I like the the video image (thumbnail), and the in-page viewing capability. My 2 cents 🤷‍♂

**Comment by lucperkins** [comment]
@chalin This is specifically in response to the Google doc shared by @jtattermusch. I'd be curious to get his input.

**Comment by jtattermusch** [comment]
The layout is looking much better now, thanks.
Would it be possible to still get thumbnails of the videos?
Also one problem with the "presentations" page is that we didn't add new content for a while, so I'm not sure if having a "Presentations" page is sustainable. If the channel is not being updated regularly, perhaps we should kill the page entirely?

**Comment by chalin** [comment]
The Docs WG has decided to go another route with this (#280). Thanks for giving it a shot. Closing.

**Pull request closed without merging**
