### PR TITLE
Format benchmarking page.

### PR DESCRIPTION
**Pull request by paulosjca**
Format with `prettier` in preparation for further changes.

@jtattermusch

### CODE REVIEW

**Comment by paulosjca** [comment]
@yashykt

**Review by jtattermusch — APPROVED** [review]
LGTM.

**Comment by jtattermusch** [comment]
@paulosjca  Let's doublecheck the updated page renders correctly before merging.

**Comment by paulosjca** [comment]
> @paulosjca Let's doublecheck the updated page renders correctly before merging.

You can check that in the "Deploy Preview" check for this PR. It looks good to me.

**Pull request merged**
