### PR TITLE
Updating headings styling

### PR DESCRIPTION
**Pull request by michalbelka**
Issue #6 

I updated heading styles to make them more readable. I had to slightly modify few other pages to make sure they still look well with new styles.

Two typography preview pages were also created, one for default view and one for two columns view used in tutorials. They are not accessible from menu so I think it's fine to keep them, but happy to remove if you feel otherwise. They may be helpful with any future styling modification.

### CODE REVIEW

**Comment by cjyabraham** [comment]
Looking good.  Now that you've got the headers fixed, I think the titles on all the guides and tutorial pages could be changed from <h3> to <h2> to differentiate them from all the <h3>s in the page content.  See [here](https://deploy-preview-32--grpc-io.netlify.com/docs/guides/auth/) or [here](https://deploy-preview-32--grpc-io.netlify.com/docs/tutorials/auth/oauth2-objective-c/) for example.

**Comment by michalbelka** [comment]
Few more edits, including ones mentioned by you and in general making whole site more consistent.

**Comment by cjyabraham** [comment]
LGTM, assigning @lucperkins to give it one final check.

**Comment by lucperkins** [comment]
@michalbelka I like the sizing and spacing changes but I find the new lighter color for larger headers (e.g. `h2`) to be much harder to read. As an illustration, compare the "Guides" header [here](https://grpc.io/docs/guides/) vs. [here](https://grpc.io/docs/guides). Personally, I would like to see the color change reverted but the sizing/spacing changes kept.

**Comment by srini100** [comment]
Ping @michalbelka

**Comment by srini100** [comment]
Closing this due to lack of response.

**Pull request closed without merging**
