### PR TITLE
README: updated instructions for building etc

### LINKED ISSUE #594: Update README with site cloning instructions now that we have submodules
We have the docsy theme as a submodule, and it has two submodules. It's easy to clone without getting the submodules and then the build won't work.

### PR DESCRIPTION
**Pull request by chalin**
Closes #594

cc @ejona86 @jtattermusch @dfawley @stanley-cheung @thisisnotapril

### CODE REVIEW

**Comment by chalin** [comment]
README instructions just don't work anymore -- ever since we completed the docsy migration. I'm going to merge this now and address any feedback in a subsequent PR. (I've locally stepped through the instructions and they seem to work well now.)

**Review by dfawley — COMMENTED** [review]
I didn't verify the steps personally, but otherwise this looks like a big improvement over what we had before.  Thank you.

**Comment by chalin** [comment]
Thanks for the feedback @dfawley!

**Comment by ejona86** [comment]
These steps look pretty straight-forward; seems basically "use like normal for hugo, if you knew how to use hugo" (but not forgetting the submodules!). Good to know there's no funny business. And the pointer to npx stuff is also helpful.

**Pull request merged**
