### PR TITLE
Add korean docs

### PR DESCRIPTION
**Pull request by cxsu**
Related: #408

And I recommend using `config.toml` for readability before more languages are added.

### CODE REVIEW

**Comment by cxsu** [comment]
sign

**Comment by veblush** [comment]
@cxsu Thanks for your contribution. Is it still in progress since most of contents under the kr directory are not fully translated.

@thisisnotapril @chalin Can you folllow up this PR? I don't know our strategy about having a translated doc.

**Comment by lidizheng** [comment]
Ping @thisisnotapril

**Comment by sergiitk** [comment]
Ping once more @thisisnotapril, @srini100.

**Comment by srini100** [comment]
Thanks for the contribution. Looks like only the index files are translated. This would be a lot of effort and future maintainence burden. Also, we'll need reviewers who can understand the language. I don't think we should go this route given some browsers have pretty good translation support in many languages. I'll close this for now. Please feel free to reopen if we want to discuss this further.

**Pull request closed without merging**
