### PR TITLE
Fix command flag bug in document

### PR DESCRIPTION
**Pull request by gozeloglu**
Fixes https://github.com/grpc/grpc.io/issues/903.

Signed-off-by: Gökhan Özeloğlu <gozeloglu@gmail.com>

Preview: https://deploy-preview-915--grpc-io.netlify.app/docs/languages/go/quickstart/

### CODE REVIEW

**Comment by gozeloglu** [comment]
Hi @easwars. Could you review my PR?

**Review by easwars — APPROVED** [review]

**Comment by easwars** [comment]
Not sure whether I have the permission to approve PRs on this repo. @dfawley @menghanl

**Comment by dfawley** [comment]
So the regression was https://github.com/grpc/grpc-go/pull/4858.  Also the instructions above this line instruct the user to `git clone -b v1.41.0`  In the 1.41 release, this was still done via the default command line arg and not a `--name` flag.

It seems we have two options:
- Update the version along with this change
- Remove the name flag added in https://github.com/grpc/grpc-go/pull/4858 (and optionally update the version alone in this repo)

**Comment by dfawley** [comment]
cc @chalin for input.

Also I'm not sure if this helloworld binary may be referenced in any other docs, which may impact this decision.

**Comment by gozeloglu** [comment]
> So the regression was [grpc/grpc-go#4858](https://github.com/grpc/grpc-go/pull/4858). Also the instructions above this line instruct the user to `git clone -b v1.41.0` In the 1.41 release, this was still done via the default command line arg and not a `--name` flag.
> 
> It seems we have two options:
> 
> * Update the version along with this change
> * Remove the name flag added in [examples: remove usage of WithBlock in examples grpc-go#4858](https://github.com/grpc/grpc-go/pull/4858) (and optionally update the version alone in this repo)

Hi @dfawley. Sorry for the late reply. For the second suggestion, do you mean removing the [name flag in this line?](https://github.com/grpc/grpc-go/blob/fbaf7c55821070944bb0ce342ba3c54cc521c6fe/examples/helloworld/greeter_client/main.go#L38)

**Review by chalin — CHANGES_REQUESTED** [review]
Based on @easwars's comment in https://github.com/grpc/grpc.io/issues/903#issuecomment-999777112, I'm ok with keeping the named flag.

But you'll need to update the code snippet (at least at line 164) of this file to match the updated example code. This is line 164, FYI:

```go
r, err = c.SayHelloAgain(ctx, &pb.HelloRequest{Name: name})
```

**Comment by dfawley** [comment]
> For the second suggestion, do you mean removing the name flag in this line?

Yes, that's what I meant by that comment.  So (1) is change this repo to match the grpc-go examples after that change and (2) is to revert the breaking part of the change in the grpc-go repo so this repo's instructions are still accurate.

**Comment by gozeloglu** [comment]
> Based on @easwars's comment in [#903 (comment)](https://github.com/grpc/grpc.io/issues/903#issuecomment-999777112), I'm ok with keeping the named flag.
> 
> But you'll need to update the code snippet (at least at line 164) of this file to match the updated example code. This is line 164, FYI:
> 
> ```go
> r, err = c.SayHelloAgain(ctx, &pb.HelloRequest{Name: name})
> ```

Hi @chalin. I didn't get why I need to change line 164. I already changed and opened PR for [Run](https://github.com/grpc/grpc.io/blob/main/content/en/docs/languages/go/quickstart.md#run) part and updated the following command 
```sh 
$ go run greeter_client/main.go Alice
```
with 
```sh
$ go run greeter_client/main.go --name=Alice
```
If we want to leave the docs as they are, I need to change [grpc-go/greeter_client/main.go](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go). I can delete `name` flag and get the name as arg and pass the name to `SayHello()` function. Maybe I need to check whether the name is passed. I am confused with your and @dfawley comments. Sorry for that.

**Comment by chalin** [comment]
@gozeloglu - I've reached out to @dfawley so that we can discuss this and suggest a way to move forward.

As I mentioned earlier, I'm in favor of merging this PR.

The change to line 164 of the markdown file is necessary because otherwise the code excerpt at that line won't reflect the changes that were made in the code at line 55, here: https://github.com/grpc/grpc-go/blob/a002994200f31f5b3e985e6b2cd2f12cb8b81389/examples/helloworld/greeter_client/main.go#L55. Does that make sense now?

**Review by chalin — APPROVED** [review]
I'm going to approve this for now. If you can fix line 164 in the markdown, that would be great. If you aren't sure what needs to be updated, I'll address it in a followup PR. (For context, see https://github.com/grpc/grpc.io/pull/915#issuecomment-1015548084).

**Comment by chalin** [comment]
Merging, after rebasing, updaing the version of gRPC Go -- as agreed with @dfawley.

**Comment by chalin** [comment]
I'll address the code change in a followup PR.

**Pull request merged**
