### PR TITLE
fix class name typo

### PR DESCRIPTION
**Pull request by DenisPavlov**

### CODE REVIEW

**Comment by chalin** [comment]
@DenisPavlov - thanks for the PR, but you'll need to sign the CLA first before we can review it.

**Comment by chalin** [comment]
@lowasser @bshaffer @jamesward - does this change make sense?

**Comment by jamesward** [comment]
Yes, the change is correct.

**Review by chalin — APPROVED** [review]
LGTM based on @jamesward's 👍

**Comment by dfawley** [comment]
Ping @DenisPavlov - can you complete the CLA please?

**Comment by DenisPavlov** [comment]
I've signed CLA but don't understand my next step. @dfawley can you help me please?

**Comment by chalin** [comment]
> I've signed CLA but don't understand my next step. @dfawley can you help me please?

You don't seem to have signed the CLA with the same ID you used to commit. The commit ID is "Павлов Денис Валерьевич". You'll need to use the same account.

**Comment by dfawley** [comment]
Ping @DenisPavlov; are you able to complete this? If not maybe send a new PR using the ID that you signed the CLA with?

**Comment by easwars** [comment]
Ping @DenisPavlov

**Comment by easwars** [comment]
@ejona86 @temawi 
Same here with an unsigned CLA.

**Comment by temawi** [comment]
I think enough time has passed for us to hope the CLA will ever get properly signed so I will close this PR.

**Comment by dfawley** [comment]
It's sad that a correctness typo can't be fixed without the user signing a CLA.  Can a maintainer send a similar PR?

**Comment by temawi** [comment]
In fact, anyone who has signed the CLA could send a similar PR 😉 

I sent out #1205, could you sanity check me @dfawley?

**Pull request closed without merging**
