### PR TITLE
Update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by chalin**

### CODE REVIEW

**Comment by ejona86** [comment]
Should we be including everyone in grpc-docs-team in the "active" list? I don't know how accurate grpc-docs-team is though.

**Comment by srini100** [comment]
@chalin, are you not going to be working on this repo anymore?

@ejona86, grcp-docs-team is not at all up to date. We'll has to be discuss this separately. We do cover open items in weekly office hours.

**Review by srini100 — APPROVED** [review]

**Comment by chalin** [comment]
> @chalin, are you not going to be working on this repo anymore?

Yes, I'm moving to other LF/CNCF projects. I'll still be making (mostly structural) changes now and again.

> @ejona86, grcp-docs-team is not at all up to date. We'll has to be discuss this separately. We do cover open items in weekly office hours.

@ejona86 says that he'd like to discuss this PR with you (@srini100) before we merge this.

**Comment by ejona86** [comment]
> @ejona86 says that he'd like to discuss this PR with you (@srini100) before we merge this.

I'd like to avoid the "None" current maintainers.

**Comment by srini100** [comment]
@chalin, can you please add srini100, thisisnotapril to the active maintainers list so it doesn't go empty due to this PR?

**Comment by chalin** [comment]
@srini100 - done, PTAL

**Comment by srini100** [comment]
LGTM.

**Review by thisisnotapril — APPROVED** [review]

**Pull request merged**
