### PR TITLE
Python: update supported versions to 3.5+, only

### PR DESCRIPTION
**Pull request by chalin**
@gnossen @lidizheng - could one of you review and approve this?

Is there a version update document for https://github.com/grpc/grpc that would ensure that updates like https://github.com/grpc/grpc/pull/19084 would be followed by a corresponding update in this repo?

### CODE REVIEW

**Review by gnossen — APPROVED** [review]

**Comment by chalin** [comment]
Thanks for the review @gnossen! Any comments on the questions in the opening comment?

**Comment by gnossen** [comment]
I'm not sure what exactly you mean by "version update document". Up to this point, we've mostly used the README visible on pypi.org and metadata in the Python wheel as the source of truth for our officially supported versions. We can add some language to our release document to make sure that we also update the documentation on the website when we drop support for an interpreter version or add support for a new one.

**Comment by chalin** [comment]
> We can add some language to our release document to make sure that we also update the documentation on the website when we drop support for an interpreter version or add support for a new one.

Yes, that would be grand, thanks! Btw, where is that "release document"?

**Comment by gnossen** [comment]
The Python release guide is an internal document detailing the release process for gRPC Python, including several sensitive steps, like how to get access to upload credentials.

**Comment by chalin** [comment]
Got it. Ok then, I'll let you add a step to that document (as mentioned above), at your discretion. Thanks!

**Pull request merged**
