### PR TITLE
Quickstart, basics: add `--depth 1` to clone command

### PR DESCRIPTION
**Pull request by chalin**
Preview, e.g.:

- https://deploy-preview-954--grpc-io.netlify.app/docs/languages/java/quickstart/#get-the-example-code
- https://deploy-preview-954--grpc-io.netlify.app/docs/languages/go/basics/#get-the-example-code

### CODE REVIEW

**Review by gnossen — APPROVED** [review]

**Comment by chalin** [comment]
> While you're at it, you might want to add `--shallow-submodules`:

Sure, I can do that in my next PR. We only want this for `grpc/grpc`, right?

**Comment by ejona86** [comment]
>> While you're at it, you might want to add --shallow-submodules:

> Sure, I can do that in my next PR. We only want this for grpc/grpc, right?

Yeah. I don't think-there-are-any/see any submodules in grpc-java, grpc-go, grpc-kotlin, and grpc-dart.

**Comment by chalin** [comment]
For context, this was in support of https://github.com/open-telemetry/opentelemetry.io/pull/1224.

**Pull request merged**
